### PR TITLE
feature/JM-6114: Allow edit of for-approval, for-reapproval and approved expenses

### PR DESCRIPTION
**Pull request by ricardofreitasrocha**
### JIRA link (if applicable) ###
[JM-6114](https://centralgovernmentcgi.atlassian.net/browse/JM-6114)

### Change description ###
- Add 'Add non attendance day' to for-approval, for-reapproval and approved flows
- Add some error handling to handle lower values being added (for-reapproval and approved only)
- Add better error handling for loss of earnings (TODO)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by gregs-cgi** [comment]
Screenshot 2024-03-22 at 15 11 48
nulls here - is this data?

**Comment by gregs-cgi** [comment]
> Screenshot 2024-03-22 at 15 11 48 Nulls here - is this data? Also should the 0 be here in red? Looks like an error (presumably because 0 isn't less than NaN), but probably shouldn't be?

I hit 'pay anyway' from here and got a hard crash:
```
     /Users/gregskinner/Projects/juror-bureau/tmp/server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js:523
              error: typeof err.error !== 'undefined' ? err.error : err.toString(),
                            ^
    
    ReferenceError: err is not defined
        at /Users/gregskinner/Projects/juror-bureau/tmp/server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js:523:25
```

**Comment by gregs-cgi** [comment]
Found a logic issue, can't lower values in 'for reapproval' (which should be able to edit down to the original approved value). I've talked to Ricardo directly with the details.

**Comment by ricardofreitasrocha** [comment]
> Found a logic issue, can't lower values in 'for reapproval' (which should be able to edit down to the original approved value). I've talked to Ricardo directly with the details.

Should be sort of fixed in the updates that followed. We made it validate in the API to account for rates changes whilst an expense was being edited too. :-)

**Comment by ricardofreitasrocha** [comment]
> > Screenshot 2024-03-22 at 15 11 48 Nulls here - is this data? Also should the 0 be here in red? Looks like an error (presumably because 0 isn't less than NaN), but probably shouldn't be?
> 
> I hit 'pay anyway' from here and got a hard crash:
> 
> ```
>      /Users/gregskinner/Projects/juror-bureau/tmp/server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js:523
>               error: typeof err.error !== 'undefined' ? err.error : err.toString(),
>                             ^
>     
>     ReferenceError: err is not defined
>         at /Users/gregskinner/Projects/juror-bureau/tmp/server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js:523:25
> ```

These should also be better handled in the updates that followed.

**Pull request merged**
